### ISSUE TITLE
How to calculate boostDM score and set cutoff?

### ISSUE THREAD

**Issue by a00101** [bbglab/boostdm-analyses#1]
I think it is not in the paper, what defined the BoostDM score, and why >0.5 is indicative for driver mutations.

thanks.

**Comment by koszulordie** [comment]
Dear Seung Jin, thanks for the question. We intended to address this question in Section 2.8 of the Supplementary Information supplied alongside the paper materials. Please, refer to that section for the details. Long story short, the boostDM score is an aggregator of forecasts (probability scores) produced by base models each trained with (random) partial views of the training data. The aggregator relies on a parameter that tunes the correction by the so-called "systematic bias" intrinsic to the base classifiers. As a result of enforcing this correction, most values of the boostDM score tend to move away from the neutral p=1/2 prediction and take informative values that are close to the (0,1) interval bounds (either p=0 or p=1) as soon as there is some level of agreement across base classifiers. In some cases it might turn out that the base classifiers do not reach a consensus view and moderate values are cast instead. Taking the neutral p=1/2 prediction value as a cutoff is a simple although natural design choice for our setting. But there may be specific models for which you might as well consider alternative approaches based on e.g. only accepting predictions that are close enough to the (0,1) interval bounds.
